;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "cljfmt-skill")
(def path ".")
(def version "0.3.1")
(def tag "0.3.1")
(def generated-at "2020-10-27T04:35:58Z")
