;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "cljformat-skill")
(def path ".")
(def version "0.1.18")
(def tag "0.1.18")
(def generated-at "2020-06-19T05:47:22Z")
