;; This code was automatically generated by the 'metav' library.
(ns atomist.skill-meta)

(def module-name "cljfmt-skill")
(def path ".")
(def version "0.2.3")
(def tag "0.2.3")
(def generated-at "2020-07-29T18:31:47Z")
